//status codes
const CODE_INVALID_REQUEST = 400;
const CODE_SUCCESSFULL = 200;
const CODE_INCORRECT_CREDITS = 401;
const CODE_UNAUTHORIZED = 401;
const CODE_NOT_FOUND = 404;

module.exports = {
	CODE_INCORRECT_CREDITS,
	CODE_NOT_FOUND,
	CODE_UNAUTHORIZED,
	CODE_SUCCESSFULL,
	CODE_INVALID_REQUEST,
};
